#!/usr/bin/env bash
# Install load balancer (HAproxy)

echo -e "Updating and performing some minor checks...\n"

# Function to install packages if not already installed
function install() {
	command -v "$1" &> /dev/null

	# Check if the package is already installed
	# shellcheck disable=SC2181
	if [ $? -ne 0 ]; then
		echo -e "Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "${1} is already installed.\n"
	fi
}

install haproxy # Install HAproxy

echo -e "\nSetting up some minor stuff.\n"

# Backup the default HAproxy configuration file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Define the custom server configuration
server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend boltage-tech-frontend
    bind *:80
    default_backend abdul-malik-tech-backend

backend abdul-malik-tech-backend
    balance roundrobin
    server web-01 135158-3.83.18.50:80 check
    server web-02 135158-54.237.117:80 check
"

# Replace the HAproxy configuration with the custom server configuration
# shellcheck disable=SC2154
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAproxy to be started by the init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Start or restart the HAproxy service
sudo service haproxy restart

echo -e "Load balancer configuration completed.\n"
